///////////////////////////////////////////////////////////
//
//  VUnitTestException.h
//  Implementation of the Class VUnitTestException
//  Generated by Enterprise Architect
//  Created on:      02-Mar-2003 20:41:27
//  Original author: sheijk
//  
///////////////////////////////////////////////////////////
//  Modification history:
//  
//
///////////////////////////////////////////////////////////


#if !defined(VUnitTestException_9B069716_CF82_43a5_A1B4_7FAD572A084C__INCLUDED_)
#define VUnitTestException_9B069716_CF82_43a5_A1B4_7FAD572A084C__INCLUDED_

#include <Error/VException.h>

#include "IVUnitTest.h"

/**
 * Exception Klasse fuer Unit Tests, soll geworfen werden wenn ein Unit
 * Test einen Fehler feststellt
 */
class VUnitTestException : public VException
{
private:
	VUnitTestException();

public:
	VUnitTestException( std::string in_strReason, 
						std::string in_strFileName, 
						vint in_nLineNumber, 
						IVUnitTest* in_pUnitTest,
						IVUnitTest::VErrorType in_ErrorType);

	virtual ~VUnitTestException();

	const IVUnitTest * GetUnitTest() const;
	IVUnitTest::VErrorType GetErrorType() const;
	std::string GetExtendedErrorString() const ;

private:
	IVUnitTest* m_pFailedTest;
	IVUnitTest::VErrorType m_ErrorType;
};

/** use this macro to throw a unit test exception */
#define V3D_THROW_UNITTEST_ERROR(error_string, error_type) \
	throw VUnitTestException(error_string, __FILE__, __LINE__, this, error_type);

#endif // !defined(VUnitTestException_9B069716_CF82_43a5_A1B4_7FAD572A084C__INCLUDED_)
